ITALIAN_MARKERS = {
    "abbastanza",
    "abbia",
    "abbiamo",
    "abbiano",
    "abbiate",
    "accanto",
    "addirittura",
    "adesso",
    "affinché",
    "allora",
    "almeno",
    "altrimenti",
    "anziché",
    "anzitutto",
    "appena",
    "avanti",
    "avendo",
    "avrebbe",
    "avrebbero",
    "avrei",
    "avresti",
    "avrete",
    "avrete",
    "avrà",
    "avranno",
    "avrò",
    "avuto",
    "avuta",
    "avuti",
    "avute",

    "benché",
    "bisogna",
    "bisognerebbe",

    "certo",
    "certamente",
    "ciascuno",
    "ciascuna",
    "cioè",
    "com'è",
    "come mai",
    "comunque",
    "conosco",
    "conosci",
    "conosce",
    "conosciuto",
    "conosciuta",
    "cosiddetto",
    "cosiddetta",
    "così",

    "dappertutto",
    "davvero",
    "dov'è",
    "dov'era",
    "dovrebbero",
    "dovrei",
    "dovresti",
    "dovrete",
    "dovrà",
    "dovranno",
    "dovrò",

    "ecco",
    "effettivamente",
    "eventualmente",

    "facciamo",
    "facendo",
    "farebbe",
    "farebbero",
    "faresti",
    "farò",
    "fatto",
    "fatta",
    "fatti",
    "fatte",
    "finché",
    "finora",
    "forse",
    "francamente",

    "giacché",
    "già",
    "giacché",
    "giornata",
    "giornate",

    "inoltre",
    "insieme",
    "invece",
    "innanzitutto",
    "insomma",

    "laggiù",
    "lassù",
    "lì",
    "l'ho",
    "l'hai",
    "l'ha",
    "l'abbiamo",
    "l'avete",
    "l'hanno",
    "l'unico",
    "l'unica",

    "medesimo",
    "medesima",
    "medesimi",
    "medesime",
    "mentre",
    "mica",
    "migliore",
    "migliori",
    "neanche",
    "nemmeno",
    "nessuno",
    "nessuna",
    "nient'altro",
    "nient'affatto",
    "nonostante",
    "ovunque",

    "parecchio",
    "parecchia",
    "parecchi",
    "parecchie",
    "perché",
    "perciò",
    "però",
    "piuttosto",
    "potrebbe",
    "potrebbero",
    "potrei",
    "potresti",
    "potrete",
    "potrà",
    "potranno",
    "potrò",
    "qualcosa",
    "qualcuno",
    "qualcuna",
    "qualcun altro",
    "qualcun'altra",
    "qualora",
    "quaggiù",
    "quassù",
    "quindi",
    "quello che",
    "quella che",
    "quelli che",
    "quelle che",
    "quello stesso",
    "quella stessa",
    "quest'ultimo",
    "quest'ultima",

    "sarebbe",
    "sarebbero",
    "sarei",
    "saresti",
    "sarete",
    "sarà",
    "saranno",
    "sarò",
    "sennò",
    "sebbene",
    "sembra",
    "sembrano",
    "sembrerebbe",
    "sempre",
    "soprattutto",
    "sottostante",
    "starei",
    "staresti",
    "stesso",
    "stessa",
    "stessi",
    "stesse",
    "succede",
    "succedere",
    "suggerirei",
    "suggeriscimi",
    "suggeritemi",

    "talmente",
    "tuttavia",
    "troppo",
    "troppa",
    "troppi",
    "troppe",

    "ugualmente",
    "un'altra",
    "un altro",
    "un'altra volta",
    "ultimamente",

    "veramente",
    "verrebbe",
    "verrebbero",
    "vorrei",
    "vorresti",
    "vorrebbe",
    "vorrebbero",
    "vorrò",

    "anche se",
    "a meno che",
    "a quanto pare",
    "a dire il vero",
    "a mio avviso",
    "a mio parere",
    "dal momento che",
    "di solito",
    "in qualche modo",
    "in ogni caso",
    "per quanto riguarda",
    "per esempio",
    "per favore",
    "per niente",
    "prima o poi",
    "secondo me",
    "senza dubbio",
}
